### ISSUE TITLE
keepa CURL connection not closing properly causing a memory leak

### ISSUE THREAD

**Issue by gokigoks** [keepacom/php_api#30] opened 2020-11-05 23:09 UTC
PHP version : 7.3
Keepa Lib version : 1.611

On the CurlClient, the curl_close is only on the __destruct method. I believe this an issue if errors are thrown due to request failure / un-checked references. This is a big problem for long running scripts. Please advice on a work-around as currently it really hurts performance and causes failures on our system.

**Comment by saschaarthur** [comment] 2020-11-06 00:57
hello,

quickly checked the code and in my opinion the code looks fine so far.. it shouldnt leak.
As a "quick" work-around i can suggest you to restart your application regulary, which normally happens automaticly in the background of most webservers.

Anyways theres a pending update for the SDK on my desk (which will happen the next couple of days), I will also have a deeper look on memory leaks and let you know.

Were you able to isolate the leaks to the SDK? Can you provide example code?

**Comment by gokigoks** [comment] 2020-11-06 02:32
Hi,

Thank you for the response. The leak is the curl connection is never closed since the only 'close' is on __destruct() or if the script ends. My use case might be unique, but we have a long running script which sends hundreds/thousands of requests to keepa and the leak incrementally adds up until it silently fails.

I believe you could  reproduce the issue by creating 2 classses (a & b), class A running a loop and instantiating class B into a variable while class B instantiates the keepaAPI class inside. Normally, every new loop, the variable class B is assigned to should be refreshed. it does, but there is a leak which we pinpointed to the curl connection not being closed.

Unfortunately, closing/restarting is out of question for us as it is a user instantiated action. Our work around is to set the keepa class variable into null to force garbage collection. All in all, this probably wont be encountered by majority, but just wanted to leave the issue here. Thanks.

**Comment by saschaarthur** [comment] 2020-11-17 18:51
Hello,

php sdk was now finally updated to 2.0.1. I also had some time to spend on this issue.
Sadly so far i was not able to reproduce the memory leak.

This is the test which im running and it seems fine and passing:

https://github.com/keepacom/php_api/compare/feature/test_leak

as you can see here

https://travis-ci.org/github/keepacom/php_api/builds/744248914

**Comment by saschaarthur** [comment] 2020-11-17 19:13
Hello,

php sdk was now finally updated to 2.0.1. I also had some time to spend on this issue.
Sadly so far i was not able to reproduce the memory leak.

This is the test which im running and it seems fine and passing:
https://github.com/keepacom/php_api/commit/952d12e940cb567f94fb008f1f3b1269230f4bb4

Also added another test (https://github.com/keepacom/php_api/commit/5248e0ef510694c84f9662f0344d370380cff100)

Result: Not even creating the API class in a loop is leaking:

https://travis-ci.org/github/keepacom/php_api/builds/744386305

Edit: rebased, updated ci-link

**Comment by saschaarthur** [comment] 2020-12-12 17:27
@gokigoks Any updates on this? Otherwise we would close the issue here, since we cant reproduce it..

**Closed as completed** 2020-12-14 17:32 UTC
